const dummyTableData = [
    // {
    //     date: "1/1/2023",
    //     transactionName: "Request for True Copy of Grades (TCG)",
    //     transactionID: 1,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
    // {
    //     date: "1/3/2023",
    //     transactionName: "Request for Leave of Absence (LOA)",
    //     transactionID: 2,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
    // {
    //     date: "1/5/2023",
    //     transactionName: "Request to Cross-register",
    //     transactionID: 3,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "1/7/2023",
    //     transactionName: "Request for True Copy of Grades (TCG)",
    //     transactionID: 4,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "1/9/2023",
    //     transactionName: "Request to Cross-register",
    //     transactionID: 5,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "1/11/2023",
    //     transactionName: "Request for Return from LOA",
    //     transactionID: 6,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
    // {
    //     date: "2/13/2023",
    //     transactionName: "Request for True Copy of Grades (TCG)",
    //     transactionID: 7,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
    // {
    //     date: "2/15/2023",
    //     transactionName: "Request for Leave of Absence (LOA)",
    //     transactionID: 8,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
    // {
    //     date: "2/17/2023",
    //     transactionName: "Request to Cross-register",
    //     transactionID: 9,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "2/19/2023",
    //     transactionName: "Request for True Copy of Grades (TCG)",
    //     transactionID: 10,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "2/21/2023",
    //     transactionName: "Request to Cross-register",
    //     transactionID: 11,
    //     transactionStatus: "Processing",
    //     action: "",      
    // },
    // {
    //     date: "3/10/2023",
    //     transactionName: "Request for Return from LOA",
    //     transactionID: 12,
    //     transactionStatus: "Pending Approval",
    //     action: "",      
    // },
]

export default dummyTableData;